project:
  type: website
  output-dir: docs

website:
  title: "Beaman's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Contact.qmd

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true

editor: visual


